/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GiftIdRouteImport } from './routes/gift.$id'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs.$id'
import { Route as ApiJobsIdKeepsakeRouteImport } from './routes/api/jobs.$id.keepsake'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftIdRoute = GiftIdRouteImport.update({
  id: '/gift/$id',
  path: '/gift/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiJobsRoute,
} as any)
const ApiJobsIdKeepsakeRoute = ApiJobsIdKeepsakeRouteImport.update({
  id: '/keepsake',
  path: '/keepsake',
  getParentRoute: () => ApiJobsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/gift/$id': typeof GiftIdRoute
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/$id/keepsake': typeof ApiJobsIdKeepsakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/gift/$id': typeof GiftIdRoute
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/$id/keepsake': typeof ApiJobsIdKeepsakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/gift/$id': typeof GiftIdRoute
  '/api/jobs/$id': typeof ApiJobsIdRouteWithChildren
  '/api/jobs/$id/keepsake': typeof ApiJobsIdKeepsakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/privacy'
    | '/terms'
    | '/api/jobs'
    | '/gift/$id'
    | '/api/jobs/$id'
    | '/api/jobs/$id/keepsake'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/privacy'
    | '/terms'
    | '/api/jobs'
    | '/gift/$id'
    | '/api/jobs/$id'
    | '/api/jobs/$id/keepsake'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/privacy'
    | '/terms'
    | '/api/jobs'
    | '/gift/$id'
    | '/api/jobs/$id'
    | '/api/jobs/$id/keepsake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiJobsRoute: typeof ApiJobsRouteWithChildren
  GiftIdRoute: typeof GiftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift/$id': {
      id: '/gift/$id'
      path: '/gift/$id'
      fullPath: '/gift/$id'
      preLoaderRoute: typeof GiftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof ApiJobsRoute
    }
    '/api/jobs/$id/keepsake': {
      id: '/api/jobs/$id/keepsake'
      path: '/keepsake'
      fullPath: '/api/jobs/$id/keepsake'
      preLoaderRoute: typeof ApiJobsIdKeepsakeRouteImport
      parentRoute: typeof ApiJobsIdRoute
    }
  }
}

interface ApiJobsIdRouteChildren {
  ApiJobsIdKeepsakeRoute: typeof ApiJobsIdKeepsakeRoute
}

const ApiJobsIdRouteChildren: ApiJobsIdRouteChildren = {
  ApiJobsIdKeepsakeRoute: ApiJobsIdKeepsakeRoute,
}

const ApiJobsIdRouteWithChildren = ApiJobsIdRoute._addFileChildren(
  ApiJobsIdRouteChildren,
)

interface ApiJobsRouteChildren {
  ApiJobsIdRoute: typeof ApiJobsIdRouteWithChildren
}

const ApiJobsRouteChildren: ApiJobsRouteChildren = {
  ApiJobsIdRoute: ApiJobsIdRouteWithChildren,
}

const ApiJobsRouteWithChildren =
  ApiJobsRoute._addFileChildren(ApiJobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiJobsRoute: ApiJobsRouteWithChildren,
  GiftIdRoute: GiftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
